# 序列化 --- 读写模型

## 读写 NDArrays
首先看一下如何读写 NDArray。

In [3]:
from mxnet import nd

x = nd.ones(3)
y = nd.zeros(4)
filename = "test1.params"
# 存下模型
nd.save(filename, [x, y])

# 读取模型
a,b = nd.load(filename)
print(a, b)

# 用来读写单个的 NDArray list,dict 也是可以的
my_dict = {"x":x,"y":y}
filename = "test2.params"
nd.save(filename, my_dict)

c = nd.load(filename)
print(c)


[1. 1. 1.]
<NDArray 3 @cpu(0)> 
[0. 0. 0. 0.]
<NDArray 4 @cpu(0)>
{'x': 
[1. 1. 1.]
<NDArray 3 @cpu(0)>, 'y': 
[0. 0. 0. 0.]
<NDArray 4 @cpu(0)>}


## 读写 Gluon 模型的参数
与 NDArray 类似，Gluon 的模型（也就是 nn.block）提供了便利的 save_params 和 load_params 函数来读写数据。和前面一样传建一个简单的多层感知机。


In [5]:
from mxnet.gluon import nn

def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(
            nn.Dense(10, activation='relu'),
            nn.Dense(2)
        )
    return net

net = get_net()
net.initialize()
x = nd.random_uniform(shape=(2, 10))
print(net(x))


[[ 0.00205935 -0.00979935]
 [ 0.00107034 -0.00423382]]
<NDArray 2x2 @cpu(0)>


In [8]:
import mxnet
# 首先将模型参数存起来
filename = "mlp.params"
net.save_params(filename)

# 然后穿件一个一样的多层感知机，但是不像前面那样随机初始化，我们直接读取前面的模型参数，
# 新的模型应该会输出同样的结果。
net2 = get_net()
net2.load_params(filename, mxnet.cpu())
print(net2(x))



[[ 0.00205935 -0.00979935]
 [ 0.00107034 -0.00423382]]
<NDArray 2x2 @cpu(0)>
